export type MenuImportStatus = 'pending' | 'processing' | 'needs_review' | 'failed' | 'published';
export type Confidence = 'high' | 'medium' | 'low';
export type ReviewReasonCode =
  | 'missing_category' | 'missing_name' | 'missing_price' | 'ambiguous_price'
  | 'merged_items' | 'price_only_name' | 'multiple_prices_in_name'
  | 'invalid_page_reference' | 'suspicious_category' | 'decorative_content'
  | 'sparse_page_inconsistency' | 'reconciliation_conflict' | 'provider_fallback'
  | 'DESCRIPTION_FRAGMENT' | 'DECORATIVE_FRAGMENT' | 'MISSING_SECTION'
  | 'AMBIGUOUS_SECTION' | 'LOW_VISUAL_CONFIDENCE';

/** Normalized [0,1] geometry relative to a rendered source page. */
export type SourceBoundingBox = { x: number; y: number; width: number; height: number };
export type NormalizedBBox = SourceBoundingBox;
export type PixelBBox = { x: number; y: number; width: number; height: number };
export type SourceGeometry = { page: number; bbox?: SourceBoundingBox; region?: string; excerpt?: string };
export type ObservedPrice = {
  raw: string;
  amount?: number | null;
  currency?: string | null;
  label?: string | null;
  shared?: boolean;
  source?: SourceGeometry;
  confidence?: Confidence;
};
export type ValidationSignal = { code: ReviewReasonCode | string; severity: 'info' | 'warning' | 'error'; detail?: string; source?: SourceGeometry };
export type ReviewReason = { code: ReviewReasonCode | string; message?: string; source?: SourceGeometry };
export type ExtractedOption = { name: string; price?: ObservedPrice; attributes?: Record<string, string>; source?: SourceGeometry };
export type ExtractedModifier = { name: string; options?: ExtractedOption[]; source?: SourceGeometry };
export type ExtractedSection = {
  key: string;
  name?: string | null;
  parentKey?: string | null;
  sortOrder?: number;
  source?: SourceGeometry;
  attributes?: Record<string, string>;
  confidence?: Confidence;
  reviewReasons?: ReviewReason[];
};
export type DocumentMetadata = { title?: string; language?: string; currency?: string | null; priceNotes?: string[]; pageCount?: number; attributes?: Record<string, string> };
export type AnalysisMetrics = {
  analyzerVersion?: string; promptVersion?: string; model?: string; pageCount?: number;
  providerCalls?: number; retryCount?: number; durationMs?: number; inputTokens?: number;
  outputTokens?: number; suspiciousPages?: number[]; fallbackReasons?: string[];
  semanticRetries?: number; regionalRetries?: number; providerTransientRetries?: number;
  recoveryRate?: number; attemptsPerPage?: Record<string, number>;
  validItemRate?: number; invalidFragmentRate?: number; pagesRequiringReview?: number;
  averageItemsPerPage?: number; mergedItemDetections?: number; categoryLeakageDetections?: number;
  fallbackUsage?: number; visualSourceRate?: number; textualSourceRate?: number;
};

export type LineageStage = 'render' | 'provider_request' | 'provider_raw' | 'decode' | 'validation' | 'retry' | 'reconciliation' | 'normalization' | 'projection' | 'persistence';
export type LineageSourceKind = 'gemini-visual' | 'textual-fallback' | 'provider-transient-retry' | 'regional-retry' | 'synthetic' | 'unknown';
/** Execution history is separate from candidate quality; it never changes acceptance. */
export type ExtractionValidationStatus = 'valid' | 'review' | 'invalid';
export type AnalysisRunId = string;
export type AnalysisAttemptId = string;
export type ExtractionCandidateId = string;
export type ExtractedItemId = string;
export type ExtractedSectionId = string;
export type ReconciledSectionId = string;
export type LineageEventId = string;

export type RenderedPageMetadata = {
  page: number;
  mimeType: string;
  width?: number;
  height?: number;
  byteSize?: number;
  contentHash?: string;
  storageReference?: string;
};

export type AuxiliaryTextEvidence = {
  source: 'native' | 'ocr' | 'selected-text' | 'unknown';
  length: number;
};

export type LineageEvent = {
  /** Generated by the server. Provider identifiers are retained only as metadata. */
  id: LineageEventId;
  analysisRunId?: AnalysisRunId;
  page?: number;
  attemptId?: AnalysisAttemptId;
  candidateId?: ExtractionCandidateId;
  itemId?: ExtractedItemId;
  sectionId?: ExtractedSectionId;
  reconciledSectionId?: ReconciledSectionId;
  parentAttemptId?: AnalysisAttemptId;
  sourceKind: LineageSourceKind;
  stage: LineageStage;
  analyzerVersion?: string;
  model?: string;
  retryReason?: string;
  regionId?: string;
  region?: NormalizedBBox;
  imageMimeType?: string;
  imageWidth?: number;
  imageHeight?: number;
  imageByteSize?: number;
  imageHash?: string;
  imageIncluded?: boolean;
  auxiliaryTextType?: string;
  auxiliaryTextLength?: number;
  latencyMs?: number;
  inputTokens?: number;
  outputTokens?: number;
  validationStatus?: ExtractionValidationStatus;
  validationReasons?: string[];
  reconciliationDecision?: string;
  rawPayloadHash?: string;
  /** Private retention only; this field must never be returned by an admin API. */
  rawPayload?: string;
  rawPayloadExpiresAt?: string;
  metadata?: Record<string, unknown>;
};

export type PageText = { page: number; text: string; source: 'native' | 'ocr' };
export type ExtractedImage = { page: number; data: Uint8Array; mimeType: string; width?: number; height?: number };
export type PdfDocument = { pages: PageText[]; images: ExtractedImage[]; usedOcr: boolean };

export type ExtractedMenuItem = {
  itemId?: ExtractedItemId;
  candidateId?: ExtractionCandidateId;
  extractionStatus?: ExtractionValidationStatus;
  retryExhausted?: boolean;
  /** Compatibility category name. Rich results should use sectionKey. */
  category?: string | null;
  sectionKey?: string | null;
  name?: string | null;
  rawName?: string | null;
  description?: string;
  ingredients?: string[];
  price?: number;
  rawPrice?: string | null;
  currency?: string | null;
  priceVariants?: ObservedPrice[];
  modifiers?: ExtractedModifier[];
  options?: ExtractedOption[];
  attributes?: Record<string, string>;
  source?: SourceGeometry;
  page: number;
  confidence: { category: Confidence; name: Confidence; description: Confidence; price: Confidence };
  validationSignals?: ValidationSignal[];
  reviewReasons?: ReviewReason[];
};

export type ImageSuggestion = { assetIndex: number; itemIndex?: number; confidence: Confidence; reason: string };
export type StructureMetadata = { provider: 'gemini' | 'local-fallback'; model?: string; fallbackReason?: string };
export type AnalysisResult = {
  items: ExtractedMenuItem[];
  images: ExtractedImage[];
  suggestions: ImageSuggestion[];
  sections?: ExtractedSection[];
  documentMetadata?: DocumentMetadata;
  metrics?: AnalysisMetrics;
  structureMetadata?: StructureMetadata;
  lineage?: LineageEvent[];
};
export type StructuredMenuOutput = Pick<AnalysisResult, 'items' | 'sections' | 'documentMetadata' | 'metrics'>;

export interface PdfAnalysisProvider {
  extractNative(pdf: Uint8Array): Promise<{ pages: PageText[]; images: ExtractedImage[] }>;
  ocr(pdf: Uint8Array): Promise<PageText[]>;
  /** Text-only provider boundary; images and source PDFs never reach structuring. */
  structure(pages: PageText[]): Promise<ExtractedMenuItem[]>;
  structureDocument?(pages: PageText[]): Promise<StructuredMenuOutput>;
  getStructureMetadata?(): StructureMetadata;
  associateImages(items: ExtractedMenuItem[], images: ExtractedImage[]): Promise<ImageSuggestion[]>;
}
